## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [53]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos_mat'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos_por'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_geo'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_ing'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_his'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos_fis'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos_qui'])

In [54]:
# 1) (operações com escalar) 
#    Calcule o percentual de acerto dos alunos por assunto:

df_mat['numero_questoes_mat'] = 24
df_mat['percentual_acertos_mat'] = df_mat['Qt_acertos_mat'] / df_mat['numero_questoes_mat']

df_por['numero_questoes_por'] = 18
df_por['percentual_acertos_por'] = df_por['Qt_acertos_por'] / df_por['numero_questoes_por']

df_geo['numero_questoes_geo'] = 8
df_geo['percentual_acertos_geo'] = df_geo['Qt_acertos_geo'] / df_geo['numero_questoes_geo']

df_ing['numero_questoes_ing'] = 8
df_ing['percentual_acertos_ing'] = df_ing['Qt_acertos_ing'] / df_ing['numero_questoes_ing']

df_his['numero_questoes_his'] = 8
df_his['percentual_acertos_his'] = df_his['Qt_acertos_his'] / df_his['numero_questoes_his']

df_fis['numero_questoes_fis'] = 12
df_fis['percentual_acertos_fis'] = df_fis['Qt_acertos_fis'] / df_fis['numero_questoes_fis']

df_qui['numero_questoes_qui'] = 12
df_qui['percentual_acertos_qui'] = df_qui['Qt_acertos_qui'] / df_qui['numero_questoes_qui']

In [55]:
df = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)
df.index += 1
df

,Qt_acertos_mat,numero_questoes_mat,percentual_acertos_mat,Qt_acertos_por,numero_questoes_por,percentual_acertos_por,Qt_acertos_geo,numero_questoes_geo,percentual_acertos_geo,Qt_acertos_ing,...,percentual_acertos_ing,Qt_acertos_his,numero_questoes_his,percentual_acertos_his,Qt_acertos_fis,numero_questoes_fis,percentual_acertos_fis,Qt_acertos_qui,numero_questoes_qui,percentual_acertos_qui
1,6,24,0.250000,7,18,0.388889,7,8,0.875,3,...,0.375,1,8,0.125,8,12,0.666667,3,12,0.250000
2,19,24,0.791667,10,18,0.555556,0,8,0.000,0,...,0.000,0,8,0.000,11,12,0.916667,8,12,0.666667
3,14,24,0.583333,16,18,0.888889,0,8,0.000,5,...,0.625,7,8,0.875,4,12,0.333333,4,12,0.333333
4,10,24,0.416667,7,18,0.388889,3,8,0.375,4,...,0.500,0,8,0.000,0,12,0.000000,8,12,0.666667
5,7,24,0.291667,2,18,0.111111,2,8,0.250,7,...,0.875,0,8,0.000,9,12,0.750000,3,12,0.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,6,24,0.250000,4,18,0.222222,7,8,0.875,1,...,0.125,4,8,0.500,9,12,0.750000,3,12,0.250000
97,8,24,0.333333,1,18,0.055556,4,8,0.500,6,...,0.750,1,8,0.125,4,12,0.333333,3,12,0.250000
98,23,24,0.958333,5,18,0.277778,0,8,0.000,2,...,0.250,4,8,0.500,1,12,0.083333,5,12,0.416667
99,0,24,0.000000,10,18,0.555556,3,8,0.375,1,...,0.125,5,8,0.625,10,12,0.833333,11,12,0.916667
100,11,24,0.458333,15,18,0.833333,0,8,0.000,1,...,0.125,6,8,0.750,7,12,0.583333,2,12,0.166667

In [56]:
# 2) (operações entre *DataFrames) 
#    Calcule o total de acertos de cada aluno:

df['qtd_acertos_total'] = df[['Qt_acertos_mat', 
                              'Qt_acertos_por', 
                              'Qt_acertos_geo', 
                              'Qt_acertos_ing', 
                              'Qt_acertos_his', 
                              'Qt_acertos_fis', 
                              'Qt_acertos_qui']].sum(axis=1)
df['qtd_acertos_total'].to_frame()

     qtd_acertos_total
1                   35
2                   48
3                   50
4                   32
5                   30
..                 ...
96                  34
97                  27
98                  40
99                  40
100                 42

[100 rows x 1 columns]

In [59]:
# 3) Calcule o porcentual geral de cada aluno:

df['qtd_questoes_total'] = df[['numero_questoes_mat',
                               'numero_questoes_por',
                               'numero_questoes_geo',
                               'numero_questoes_ing',
                               'numero_questoes_his',
                               'numero_questoes_fis',
                               'numero_questoes_qui']].sum(axis=1)
df['percentual_geral'] = df['qtd_acertos_total'] / df['qtd_questoes_total']
df

,Qt_acertos_mat,numero_questoes_mat,percentual_acertos_mat,Qt_acertos_por,numero_questoes_por,percentual_acertos_por,Qt_acertos_geo,numero_questoes_geo,percentual_acertos_geo,Qt_acertos_ing,...,percentual_acertos_his,Qt_acertos_fis,numero_questoes_fis,percentual_acertos_fis,Qt_acertos_qui,numero_questoes_qui,percentual_acertos_qui,qtd_acertos_total,qtd_questoes_total,percentual_geral
1,6,24,0.250000,7,18,0.388889,7,8,0.875,3,...,0.125,8,12,0.666667,3,12,0.250000,35,90,0.388889
2,19,24,0.791667,10,18,0.555556,0,8,0.000,0,...,0.000,11,12,0.916667,8,12,0.666667,48,90,0.533333
3,14,24,0.583333,16,18,0.888889,0,8,0.000,5,...,0.875,4,12,0.333333,4,12,0.333333,50,90,0.555556
4,10,24,0.416667,7,18,0.388889,3,8,0.375,4,...,0.000,0,12,0.000000,8,12,0.666667,32,90,0.355556
5,7,24,0.291667,2,18,0.111111,2,8,0.250,7,...,0.000,9,12,0.750000,3,12,0.250000,30,90,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,6,24,0.250000,4,18,0.222222,7,8,0.875,1,...,0.500,9,12,0.750000,3,12,0.250000,34,90,0.377778
97,8,24,0.333333,1,18,0.055556,4,8,0.500,6,...,0.125,4,12,0.333333,3,12,0.250000,27,90,0.300000
98,23,24,0.958333,5,18,0.277778,0,8,0.000,2,...,0.500,1,12,0.083333,5,12,0.416667,40,90,0.444444
99,0,24,0.000000,10,18,0.555556,3,8,0.375,1,...,0.625,10,12,0.833333,11,12,0.916667,40,90,0.444444
100,11,24,0.458333,15,18,0.833333,0,8,0.000,1,...,0.750,7,12,0.583333,2,12,0.166667,42,90,0.466667

In [60]:
# 4) Suponha que a nota de corte para a segunda fase seja 45. 
#    Quantos alunos tiveram nota maior que 45?

segunda_fase = df[df['qtd_acertos_total'] > 45]

print('Quantidade de alunos com nota maior que 45:')
print(segunda_fase.shape[0])

Quantidade de alunos com nota maior que 45:
31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [61]:
# 1) Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. 
#    Monte um novo DataFrame com os alunos desqualificados por este critério:

desqualificados = df[(df['Qt_acertos_mat'] == 0) | 
                     (df['Qt_acertos_fis'] == 0) | 
                     (df['Qt_acertos_qui'] == 0)]

desqualificados[['Qt_acertos_mat', 'Qt_acertos_fis', 'Qt_acertos_qui']]

    Qt_acertos_mat  Qt_acertos_fis  Qt_acertos_qui
4               10               0               8
7                6               0               4
11              10               7               0
13              20               0               3
15               7               4               0
21              23               2               0
26               0               4               8
27              11               0               0
28              21               3               0
34              14               6               0
36              11               0              11
50               8               0               8
57               7               0               8
66               1               0               6
67               5               0              10
73              11               0               9
74               1               0              11
75               9               7               0
85              15               0               4
90              23               9               0
93              14               8               0
95               0               3               8
99               0              10              11

In [62]:
# 2) Quantos são esses alunos?

print(f'Total de alunos desqualificados: {desqualificados.shape[0]}.')

Total de alunos desqualificados: 23.

In [63]:
# 3) Qual a média desses alunos em história e geografia?

media_desqualificados_his = round(desqualificados['Qt_acertos_his'].mean(), 2)
media_desqualificados_geo = round(desqualificados['Qt_acertos_geo'].mean(), 2)

print('Média dos alunos desqualificados nas 8 questões de história: {}.'.format(media_desqualificados_his))
print('Média dos alunos desqualificados nas 8 questões de geografia: {}.'.format(media_desqualificados_geo))

Média dos alunos desqualificados nas 8 questões de história: 3.43.
Média dos alunos desqualificados nas 8 questões de geografia: 3.22.

In [64]:
# 4) Monte um DataFrame com os alunos que passaram para a segunda fase. 
#    Repare que estes alunos não podem ter sido desqualificados.

# Juntando dois dataframes somente com as linhas em comum:
segunda_fase_desqualificados = pd.merge(left=segunda_fase, 
                                        right=desqualificados,
                                        how='inner')
segunda_fase_desqualificados

,Qt_acertos_mat,numero_questoes_mat,percentual_acertos_mat,Qt_acertos_por,numero_questoes_por,percentual_acertos_por,Qt_acertos_geo,numero_questoes_geo,percentual_acertos_geo,Qt_acertos_ing,...,percentual_acertos_his,Qt_acertos_fis,numero_questoes_fis,percentual_acertos_fis,Qt_acertos_qui,numero_questoes_qui,percentual_acertos_qui,qtd_acertos_total,qtd_questoes_total,percentual_geral
0,23,24,0.958333,11,18,0.611111,6,8,0.750,5,...,0.750,2,12,0.166667,0,12,0.000000,53,90,0.588889
1,21,24,0.875000,13,18,0.722222,1,8,0.125,5,...,0.875,3,12,0.250000,0,12,0.000000,50,90,0.555556
2,11,24,0.458333,14,18,0.777778,6,8,0.750,3,...,0.375,0,12,0.000000,11,12,0.916667,48,90,0.533333
3,11,24,0.458333,16,18,0.888889,3,8,0.375,4,...,0.875,0,12,0.000000,9,12,0.750000,50,90,0.555556
4,23,24,0.958333,11,18,0.611111,7,8,0.875,7,...,0.750,9,12,0.750000,0,12,0.000000,63,90,0.700000

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [67]:
# arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'
arquivo = 'registros de vacinacao covid ACRE.csv'

df = pd.read_csv(arquivo, sep=';')

In [68]:
df.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,bb4e0d0c-527e-4a44-8119-4ff29f6babc1-i0b0,ddb51020757ff314e49549bd5129ef8942c3ca88c49376...,15,2006-01-25,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FG3533,PFIZER,Organization/00394544000851,2021-10-28,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
1,972910f2-1b61-420d-ad84-639e2aba517c-i0b0,bff54352ea247e14008f21ccd407944bddbc82e5b31c20...,5,2017-02-27,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,NaN,NaN,FP0362,PFIZER - PEDIÁTRICA,28290,2022-12-08,2ª Dose,99,COVID-19 PFIZER - COMIRNATY PEDIÁTRICA,Novo PNI
2,c909da1d-f39c-4665-a5ff-af308b957f88-i0b0,931db3a82ae88b833fc112449d93de823b9519b60e651d...,36,1985-04-28,F,99,SEM INFORMACAO,120020.0,10.0,CRUZEIRO DO SUL,...,2.0,Faixa Etária,212VCD003ZVAA,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-07-02,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
3,97f13a8d-0305-45cb-b875-c3a9d1be160c-i0b0,08a0f3b2dd81019b38298cd3a56461cb757308b296bcbb...,25,1997-11-29,F,4,AMARELA,120070.0,10.0,XAPURI,...,2.0,Faixa Etária,220301,SINOVAC/BUTANTAN,152,2023-03-21,Revacinação,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
4,a977448f-a4aa-4bb7-a887-07bfcd130915-i0b0,5c51912989b69feda9bbb5320ac13a34261e037f3d8620...,14,2008-05-10,M,4,AMARELA,120070.0,10.0,XAPURI,...,2.0,Faixa Etária,FX1188,PFIZER,28290,2023-03-06,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [76]:
# 1) Quantas vacinas estão registradas nessa base?

print('Quantidade de vacinas na base de dados:')
print(df.shape[0])

Quantidade de vacinas na base de dados:
387484

In [75]:
# 1) Quantas vacinas estão registradas nessa base?

print('Quantidade de vacinas na base de dados:')
print(df.shape[0])

Quantidade de vacinas na base de dados:
387484

In [77]:
# 2) Quantos pacientes foram vacinados? 
#    (considere um paciente para cada valor único de paciente_id)

print('Quantidade de pacientes vacinados:')
print(df['paciente_id'].nunique())

Quantidade de pacientes vacinados:
316719

In [79]:
# 3) Quantos pacientes únicos tomaram a primeira dose? 
#    OBS: Há um caractere especial neste campo. 
#    Receba os valores do campo com o método .unique().

primeira_dose = df['vacina_descricao_dose'].unique()[0]
df_pacientes_primeira_dose = df[df['vacina_descricao_dose'] == primeira_dose]
numero_pacientes_primeira_dose = df_pacientes_primeira_dose['paciente_id'].nunique()

print('Quantidade de pacientes que tomaram a primeira dose:')
print(numero_pacientes_primeira_dose)

Quantidade de pacientes que tomaram a primeira dose:
143288

In [78]:
# 3) Quantos pacientes únicos tomaram a primeira dose? 
#    OBS: Há um caractere especial neste campo. 
#    Receba os valores do campo com o método .unique().

primeira_dose = df['vacina_descricao_dose'].unique()[0]
df_pacientes_primeira_dose = df[df['vacina_descricao_dose'] == primeira_dose]
numero_pacientes_primeira_dose = df_pacientes_primeira_dose['paciente_id'].nunique()

print('Quantidade de pacientes que tomaram a primeira dose:')
print(numero_pacientes_primeira_dose)

Quantidade de pacientes que tomaram a primeira dose:
143288

In [80]:
# 4) Quantos pacientes com menos de 18 anos foram vacinados?

df_menores_18_anos = df[df['paciente_idade'] < 18]
qtd_menores_18_anos = df_menores_18_anos['paciente_id'].nunique()

print('Quantidade de pacientes menores de 18 anos:')
print(qtd_menores_18_anos)

Quantidade de pacientes menores de 18 anos:
68419

In [84]:
# 5) Quantos estabelecimentos aplicaram vacina no Acre?

# Entendendo as colunas de estabelecimento:
df.loc[:,'estabelecimento_valor':'estabelecimento_uf']

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
0,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
1,2001101,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA RAIMUNDA BITENCOUR...,120080,PORTO ACRE,AC
2,7247435,PREFEITURA MUNICIPAL DE SAUDE,UNIDADE DE SAUDE DA FAMILIA RAIMUNDO CELSO LIM...,120020,CRUZEIRO DO SUL,AC
3,2001934,PREFEITURA MUNICIPAL DE XAPURI,UNIDADE DE SAUDE DA FAMILIA JOSE RAIMUNDO DE MELO,120070,XAPURI,AC
4,2001217,PREFEITURA MUNICIPAL DE XAPURI,UNIDADE SAUDE DA FAMILIA JOSE FADUL,120070,XAPURI,AC
...,...,...,...,...,...,...
387479,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
387480,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
387481,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
387482,2000342,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE DA FAMILIA ABEL PINHEIRO,120020,CRUZEIRO DO SUL,AC
387483,2000016,PREFEITURA MUNICIPAL DE RODRIGUES ALVES,UNIDADE BASICA PADRE TEODORO ARNDS,120042,RODRIGUES ALVES,AC

In [94]:
print("Quantidade de valores únicos da coluna 'estabelecimento_valor':")
print(df['estabelecimento_valor'].nunique())

print()

print("Quantidade de valores únicos da coluna 'estabelecimento_razaoSocial':")
print((df['estabelecimento_razaoSocial'].nunique()))

Quantidade de valores únicos da coluna 'estabelecimento_valor':
223

Quantidade de valores únicos da coluna 'estabelecimento_razaoSocial':
62

In [95]:
# Valores diferentes de estabelecimento identificados no mesmo valor de razão social:

# Como a quantidade de valores da coluna 'estabelecimento_valor' é maior,
# provavelmente a coluna 'estabelecimento_razaosocial' contém valores repetidos

# criando novo dataframe somente com duas colunas:
dupl = df[['estabelecimento_razaoSocial', 'estabelecimento_valor']].copy()

# retirando os valores duplicados da coluna 'estabelecimento_valor':
dupl = dupl.drop_duplicates(subset='estabelecimento_valor')

# filtrando o dataframe somente com os valores que se repetem na coluna 'estabelecimento_razaosocial':
dupl = dupl[dupl['estabelecimento_razaoSocial'].duplicated(keep=False)]

pd.options.display.max_rows = 102

dupl.reset_index(drop=True, inplace=True)
dupl.set_index('estabelecimento_razaoSocial', inplace=True)
dupl.sort_index(ascending=True)

                                                    estabelecimento_valor
estabelecimento_razaoSocial
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO J...                7625855
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO J...                6308740
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO J...                6955525
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO J...                6917682
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO J...                6748759
...                                                                   ...
SECRETARIA DE ESTADO DE SAUDE DO ACRE                             9966501
SECRETARIA DE ESTADO DE SAUDE DO ACRE                             2000814
SECRETARIA MUNICIPAL DE SAUDE                                     2002922
SECRETARIA MUNICIPAL DE SAUDE                                      783722
SECRETARIA MUNICIPAL DE SAUDE                                     9896392

[189 rows x 1 columns]

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [86]:
df_menores_18 = df[df['paciente_idade'] < 18].copy()
df_menores_18.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77526 entries, 0 to 387482
Data columns (total 32 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   document_id                               77526 non-null  object
 1   paciente_id                               77526 non-null  object
 2   paciente_idade                            77526 non-null  int64
 3   paciente_dataNascimento                   77526 non-null  object
 4   paciente_enumSexoBiologico                77526 non-null  object
 5   paciente_racaCor_codigo                   77526 non-null  int64
 6   paciente_racaCor_valor                    77526 non-null  object
 7   paciente_endereco_coIbgeMunicipio         76921 non-null  float64
 8   paciente_endereco_coPais                  76922 non-null  float64
 9   paciente_endereco_nmMunicipio             76922 non-null  object
 10  paciente_endereco_nmPais                  76922 non-null  object
 11  paciente_endereco_uf                      76921 non-null  object
 12  paciente_endereco_cep                     62585 non-null  float64
 13  paciente_nacionalidade_enumNacionalidade  77521 non-null  object
 14  estabelecimento_valor                     77526 non-null  int64
 15  estabelecimento_razaoSocial               77526 non-null  object
 16  estalecimento_noFantasia                  77526 non-null  object
 17  estabelecimento_municipio_codigo          77526 non-null  int64
 18  estabelecimento_municipio_nome            77526 non-null  object
 19  estabelecimento_uf                        77526 non-null  object
 20  vacina_grupoAtendimento_codigo            77526 non-null  int64
 21  vacina_grupoAtendimento_nome              76330 non-null  object
 22  vacina_categoria_codigo                   57368 non-null  float64
 23  vacina_categoria_nome                     57368 non-null  object
 24  vacina_lote                               77526 non-null  object
 25  vacina_fabricante_nome                    77526 non-null  object
 26  vacina_fabricante_referencia              75574 non-null  object
 27  vacina_dataAplicacao                      77526 non-null  object
 28  vacina_descricao_dose                     77526 non-null  object
 29  vacina_codigo                             77526 non-null  int64
 30  vacina_nome                               77517 non-null  object
 31  sistema_origem                            77416 non-null  object
dtypes: float64(4), int64(6), object(22)
memory usage: 19.5+ MB

In [87]:
# 2) Crie uma lista das colunas desse DataFrame com o atributo de DataFrame .columns()

colunas_df_menores_18 = df_menores_18.columns
colunas_df_menores_18

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [88]:
# 3) Nesse DataFrame faça uma contagem do campo vacina_categoria_nome:

print("Quantidade de valores na coluna 'vacina_categoria_nome':")
print(df_menores_18['vacina_categoria_nome'].count())

print()

print("Quantidade de valores únicos na coluna 'vacina_categoria_nome':")
print(df_menores_18['vacina_categoria_nome'].nunique())

print()

print(df_menores_18['vacina_categoria_nome'].value_counts())

Quantidade de valores na coluna 'vacina_categoria_nome':
57368

Quantidade de valores únicos na coluna 'vacina_categoria_nome':
13

vacina_categoria_nome
Faixa Etária                                      47636
Povos Indígenas                                    4723
Outros                                             3755
Povos e Comunidades Tradicionais                    828
Trabalhadores de Saúde                              257
Comorbidades                                         56
População Privada de Liberdade                       53
Gestantes                                            42
Pessoas com Deficiência                              11
Pessoas Institucionalizadas                           3
Trabalhadores da Educação                             2
Pessoas de 60 anos ou mais institucionalizadas        1
Puérperas                                             1
Name: count, dtype: int64

In [89]:
# 4) A partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, 
#    faça uma lista com esses valores:

# colunas_estabelecimentos_df_menores_18 = [coluna for coluna in colunas_df_menores_18 if coluna.startswith('estabelecimento')]
colunas_estabelecimentos_df_menores_18 = colunas_df_menores_18[14:20]
colunas_estabelecimentos_df_menores_18

Index(['estabelecimento_valor', 'estabelecimento_razaoSocial',
       'estalecimento_noFantasia', 'estabelecimento_municipio_codigo',
       'estabelecimento_municipio_nome', 'estabelecimento_uf'],
      dtype='object')

In [90]:
# 5) Usando o método .loc, selecione somente essas variáveis:

df_menores_18.loc[:,colunas_estabelecimentos_df_menores_18]

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
0,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
1,2001101,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA RAIMUNDA BITENCOUR...,120080,PORTO ACRE,AC
4,2001217,PREFEITURA MUNICIPAL DE XAPURI,UNIDADE SAUDE DA FAMILIA JOSE FADUL,120070,XAPURI,AC
5,2000512,PREFEITURA MUNICIPAL DE RIO BRANCO,URAP EDUARDO ASSMAR,120040,RIO BRANCO,AC
9,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
...,...,...,...,...,...,...
387446,2002922,SECRETARIA MUNICIPAL DE SAUDE,U S F JOAO DE DEUS,120038,PLACIDO DE CASTRO,AC
387451,924490,PREFEITURA MUNICIPAL DE FEIJO,UNIDADE MOVEL DE SAUDE FLUVIAL PEDRO RODRIGUES...,120030,FEIJO,AC
387470,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
387476,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
387482,2000342,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE DA FAMILIA ABEL PINHEIRO,120020,CRUZEIRO DO SUL,AC

In [96]:
# 6) Aplique o método .drop_duplicates e 
#    crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento:

lista_estabelecimentos_df_menores_18 = df_menores_18['estabelecimento_razaoSocial'].drop_duplicates()
lista_estabelecimentos_df_menores_18.reset_index(drop=True, inplace=True)
lista_estabelecimentos_df_menores_18.index += 1
lista_estabelecimentos_df_menores_18.to_frame()

                          estabelecimento_razaoSocial
1                  PREFEITURA MUNICIPAL DE RIO BRANCO
2                  PREFEITURA MUNICIPAL DE PORTO ACRE
3                      PREFEITURA MUNICIPAL DE XAPURI
4               PREFEITURA MUNICIPAL DE MANUEL URBANO
5   DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...
6                    PREFEITURA MUNICIPAL DE TARAUACA
7     DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA
8                      PREFEITURA MUNICIPAL DE JORDAO
9                   PREFEITURA MUNICIPAL DE BRASILEIA
10                  PREFEITURA MUN DE MAL THAUMATURGO
11                      PREFEITURA MUNICIPAL DE FEIJO
12             PREFEITURA MUNICIPAL DE SENA MADUREIRA
13                       SECRETARIA MUNCIPAL DE SAUDE
14               PREFEITURA MUNICIPAL DE ASSIS BRASIL
15            PREFEITURA MUNICIPAL DE RODRIGUES ALVES
16                      SECRETARIA MUNICIPAL DE SAUDE
17                              POLO BASE DE TARAUACA
18            PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL
19                            MUNICIPIO DE RIO BRANCO
20               PREFEITURA MUNICIPAL DE PORTO WALTER
21           PREFEITURA MUNICIPAL DE SENADOR GUIOMARD
22                                      REDE DE FRIOS
23        PREFEITURA MUNICIPAL DE SANTA ROSA DO PURUS
24            PREFEITURA MUNICIIPAL DE SENA MADUREIRA
25                           MUNICIPIO DE MANCIO LIMA
26                      PREFEITURA MUNICIPAL DE SAUDE
27  DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...
28             PREFEITURA MUNICIPAL DE EPITACIOLANDIA
29                 PREFEITURA MUNICIPAL DE ACRELANDIA
30                PREFEITURA MUNICIPAL DE MANCIO LIMA
31                   PREFEITURA MUNICIPAL MANCIO LIMA
32                   PREFEITURA MUNICIPAL DE CAPIXABA
33                      SECRETARIA DE ESTADO DE SAUDE
34  DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...
35                                USF AEROPORTO VELHO
36                            PREFEITURA DE BRASILEIA
37                          PREFEITURA DE MANCIO LIMA
38                                MINISTERIO DA SAUDE
39                     PREFEITURA MUNICIPAL DE BUJARI
40                                USF LIDIA RODRIGUES
41                   MUNICIPIO DE SANTA ROSA DO PURUS
42                  MUNICIPIO DE MARECHAL THAUMATURGO
43                             MUNICIPIO DE BRASILEIA
44                          MUNICIPIO DE PORTO WALTER
45                    PREFEITURA MUNICIPAL DE SENADOR
46              SECRETARIA DE ESTADO DE SAUDE DO ACRE
47                      MUNICIPIO DE SENADOR GUIOMARD
48                       PREFEITURA DE SENA MADUREIRA
49       PREFEITURA MUNICIPAL DE MARECHAL THAUMATURGO
50                                K M OLIVEIRA EIRELI
51              PREFEITURA MUNICIPAL DE MANOEL URBANO
52                 CENTRAL MUNICIPAL DE REDE DE FRIOS
53          PREFEITURA MUNICIPAL DE PLACIDO DE CASTRO
54         SECRETARIA MUNICIPAL DE SAUDE DE BRASILEIA
55                                 USF BARRO VERMELHO